### PR TITLE
WIP PR

### PR DESCRIPTION
**Pull request by anupriyakkumari**
Created assignment_name_myname (Git-Bash_Anupriya) directory within myname (Anupriya) directory inside the lecture-assignments-y23 repo as asked. Created README.md inside Git-Bash_Anupriya and also the .sh files that were needed while solving missing semester exercises. Currently editing the README.md as I progress.

### CODE REVIEW

**Comment by guptaaryan16** [comment]
@anupriyakkumari Nice work done till now

**Comment by guptaaryan16** [comment]
Please change the title of PR to `Git+Bash Assignment - <your_name>[WIP]`

**Comment by anupriyakkumari** [comment]
So I messed up a little bit, I was checking out git commands and I created
a new branch and accidentally created the PR from that branch. I realised
it was a bit messy and after the PR got closed, pushing was causing issues
cause of merge conflicts so now I have removed that branch and will be
pushing through the main branch. That's why the initial PR got removed.

**Comment by guptaaryan16** [comment]
Hey @anupriyakkumari it is okay and these things happen initially. What you can do is create a new branch in your fork and make all the changes. You can  also delete your fork and then make all the changes you want. For merge conflicts try to install git extensions in VSCode as they are very handy and try to complete the git immersion first as it can help you with the PRs

**Pull request closed without merging**
