### PR TITLE
Git-Bash_SomShekhar

### PR DESCRIPTION
**Pull request by ReallyJaegar**

### CODE REVIEW

**Comment by divo12** [comment]
@ReallyJaegar When do you plan to push your work?

**Comment by ReallyJaegar** [comment]
problem 1,2,3,5 completed problem 4 in progress

**Comment by ReallyJaegar** [comment]
all problems completed

**Comment by Pradnya2203** [comment]
add readme in [scriptautomater](https://github.com/ReallyJaegar/lecture-assignments-y23/tree/main/Git-Bash/Som_Shekhar/Git-Bash_Som/scriptautomater)
Also you are getting merge conflicts, try to solve them

**Pull request merged**
