### PR TITLE
Git-Bash_Aayan [WIP]

### PR DESCRIPTION
**Pull request by ydvaayan**

### CODE REVIEW

**Comment by guptaaryan16** [comment]
@ydvaayan You have done a great job in the assignment, but not have mentioned anything for the git immersion part so I am assuming you had nothing to write for that. Please try to increase your documentation skills a bit in future though. Thanks for the assignment 

@divo12 Ready for merge

**Comment by ydvaayan** [comment]
> @ydvaayan You have done a great job in the assignment, but not have mentioned anything for the git immersion part so I am assuming you had nothing to write for that. Please try to increase your documentation skills a bit in future though. Thanks for the assignment 
> 
> @divo12 Ready for merge

I tried to explain and give solutions for git-immersion in Git Immersion.md . Could you please clarify what else was expected out of me in that particular question?

**Comment by guptaaryan16** [comment]
hey @ydvaayan my idea for git immersion and bandit was that you will document only important commands and write some good interpretations based on the research you may do on the same. But it looks like you just copy pasted the commands and their outputs which is fine for now but can be improved in the future

**Comment by ydvaayan** [comment]
> hey @ydvaayan my idea for git immersion and bandit was that you will document only important commands and write some good interpretations based on the research you may do on the same. But it looks like you just copy pasted the commands and their outputs which is fine for now but can be improved in the future

Okay, thanks for the review !

**Pull request merged**
